<div style="background: url(https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExenVtNGVzaG45dmR2ejg3dGgweXF5MjdyYmtqM25wZnExMzZsaTFiOCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/xTiTnxpQ3ghPiB2Hp6/giphy.webp) repeat; color: #00ff00; padding: 2px; text-align: center;background-size: cover; text-shadow: 00 0 20px #ec4899">
    <h1>Learning Pandas for DataAnalysis Starthere</h1>
    
</div>

1. [`Colors`](https://rich.readthedocs.io/en/latest/appendix/colors.html?highlight=colors) _ list of standard colors that can be printed out 
2. [`Ascii Banne Generator`](https://manytools.org/hacker-tools/ascii-banner/) - Used this to generate nice banners below 
3. [`AsciiFlow`](https://asciiflow.com/#/) - Draw ASCII digrams you can then use this

<div style="background-color: #000502; color: #16a34a; padding: 10px; border-radius: 5px; font-size: 25px; text-align:center">
  <a class="anchor" id="toc" style="text-decoration: none;">Table of Contents</a>
</div>

- ### [Lesson Summary](#s0)
- ### [1-IntroPandasIntroPandas](#s1)
- ### [2-I/O](#s2)
- ### [3-DataFrameBsicsDataFrameBsics](#s3)

In [2]:
# Prettify 
# Prettifyer code

# ------------------------------------------------------
from rich import print as rprint # For rprinting
from rich.pretty import pprint # For pretty printing
from rich import inspect # For inspect
from rich.console import Console # For console.print
from rich.markdown import Markdown # For markdown
from rich.panel import Panel # For Panel()
from rich import box # For Panel Boxes
from rich.prompt import Prompt # For Prompting 
from rich.style import Style # For styles colors
from rich.text import Text # For text Styles
console = Console() # Standard code to access console
from rich.traceback import install
install(show_locals=True)
# -------------------------------------------------------

# Lesson Summary <a class="anchor" id="s0"></a> [↩️TOC](#toc)

1. This notebook is for woking on [`THIS`](https://youtu.be/DkjCaAMBGWM?si=wIPJl3W1pjocA_n3)
2. Used for data wrangling and data manipulation.

In [6]:
# Current Date Time 
import datetime

current_date = datetime.datetime.now()
rprint(current_date.strftime("%A, %B %d, %Y"))

Monday, July 29, 2024

# 1.IntroPandas <a class="anchor" id="s1"></a> [↩️TOC](#toc)

# Work with pandas
- This will printout the pandas version 
- Printing both the python version and Pandas version 
- As of date of making this notebook the [`Pandas`](https://pandas.pydata.org/) version is - `2.2.2` - Same as the oen which this notebook uses

In [8]:
import pandas as pd 
import sys 

# Printing the python version
rprint(sys.version) 

# Printing the pandas version
rprint('Pandas Kag Version:- ',pd.__version__)

3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:39) [GCC 12.3.0]

Pandas Kag Version:-  2.2.2

# 2.I/O <a class="anchor" id="s2"></a> [↩️TOC](#toc)

1. `pd.read_csv` - Most used option
2. Note the tutorial works with parquet files , so have to first get some parquet files and then continue 
3. [`Tutorial Notebook`](https://www.kaggle.com/code/lizhecheng/pandas-2-0-1-tutorial/notebook) - This is the tutorial notebook with the data set which is being used in this course. Will dl file , and ul to gh , then use remote load from addinput
- This above notebook actually is using kaggle datasets which have the parquet format 
4. Dataset being used
    1. (`inflight-emergency-situations`)[https://www.kaggle.com/datasets/ahmedeltom/inflight-emergency-situations-20182020]

In [9]:
!pip install -q pandas pyarrow

- This above library was mentioned in the dataset to install

In [10]:
# Reading the dataset
df = pd.read_parquet('/kaggle/input/inflight-emergency-situations-20182020/trajectories.parquet')

In [11]:
type(df)

pandas.core.frame.DataFrame

Coversion of the parquet dataset to csv

In [12]:
df.to_csv('myCon.csv', index=False)

In [18]:
# Now load this into another dataframe 
df2 = pd.read_csv('myCon.csv')

In [23]:
# Viewing the csv format
df2.head(10) #View Head

,timestamp,altitude,callsign,flight_id,groundspeed,icao24,latitude,longitude,squawk,track,vertical_rate
0,2018-01-01 12:29:49+00:00,11300.0,ARG1511,ARG1511_20180101,309.885195,e06442,-31.449051,-63.963318,7700,130.441641,3008.000000
1,2018-01-01 12:29:50+00:00,11375.0,ARG1511,ARG1511_20180101,310.264709,e06442,-31.450453,-63.961432,7700,130.441641,3040.000000
2,2018-01-01 12:29:51+00:00,11450.0,ARG1511,ARG1511_20180101,310.644223,e06442,-31.451856,-63.959546,7700,130.441641,3072.000000
3,2018-01-01 12:29:52+00:00,11500.0,ARG1511,ARG1511_20180101,311.192793,e06442,-31.452843,-63.958193,7700,130.440361,3074.742857
4,2018-01-01 12:29:53+00:00,11550.0,ARG1511,ARG1511_20180101,311.741363,e06442,-31.453831,-63.956840,7700,130.439081,3077.485714
5,2018-01-01 12:29:54+00:00,11600.0,ARG1511,ARG1511_20180101,312.289932,e06442,-31.454818,-63.955487,7700,130.437801,3080.228571
6,2018-01-01 12:29:55+00:00,11650.0,ARG1511,ARG1511_20180101,312.838502,e06442,-31.455806,-63.954134,7700,130.436521,3082.971429
7,2018-01-01 12:29:56+00:00,11700.0,ARG1511,ARG1511_20180101,313.387072,e06442,-31.456794,-63.952781,7700,130.435240,3085.714286
8,2018-01-01 12:29:57+00:00,11750.0,ARG1511,ARG1511_20180101,313.935642,e06442,-31.457781,-63.951429,7700,130.433960,3088.457143
9,2018-01-01 12:29:58+00:00,11800.0,ARG1511,ARG1511_20180101,314.484211,e06442,-31.458769,-63.950076,7700,130.432680,3091.200000

In [22]:
# View the tail 
df2.tail(10)

,timestamp,altitude,callsign,flight_id,groundspeed,icao24,latitude,longitude,squawk,track,vertical_rate
4344349,2020-01-29 04:09:43+00:00,659.375000,ASH6299,ASH6299_20200129,137.440778,ac2bb8,40.002629,-82.897304,2756,274.590543,-704.0
4344350,2020-01-29 04:09:44+00:00,658.333333,ASH6299,ASH6299_20200129,137.440778,ac2bb8,40.002656,-82.897768,2756,274.590543,-704.0
4344351,2020-01-29 04:09:45+00:00,657.291667,ASH6299,ASH6299_20200129,137.440778,ac2bb8,40.002683,-82.898231,2756,274.590543,-704.0
4344352,2020-01-29 04:09:46+00:00,656.250000,ASH6299,ASH6299_20200129,137.440778,ac2bb8,40.002709,-82.898694,2756,274.590543,-704.0
4344353,2020-01-29 04:09:47+00:00,655.208333,ASH6299,ASH6299_20200129,137.440778,ac2bb8,40.002736,-82.899158,2756,274.590543,-704.0
4344354,2020-01-29 04:09:48+00:00,654.166667,ASH6299,ASH6299_20200129,137.440778,ac2bb8,40.002762,-82.899621,2756,274.590543,-704.0
4344355,2020-01-29 04:09:49+00:00,653.125000,ASH6299,ASH6299_20200129,137.440778,ac2bb8,40.002789,-82.900084,2756,274.590543,-704.0
4344356,2020-01-29 04:09:50+00:00,652.083333,ASH6299,ASH6299_20200129,137.440778,ac2bb8,40.002816,-82.900547,2756,274.590543,-704.0
4344357,2020-01-29 04:09:51+00:00,651.041667,ASH6299,ASH6299_20200129,137.440778,ac2bb8,40.002842,-82.901011,2756,274.590543,-704.0
4344358,2020-01-29 04:09:52+00:00,650.000000,ASH6299,ASH6299_20200129,137.440778,ac2bb8,40.002869,-82.901474,2756,274.590543,-704.0

# 2.DataFrameBsics <a class="anchor" id="s3"></a> [↩️TOC](#toc)

In [25]:
# Viw first 5 rows 
df.head()

,timestamp,altitude,callsign,flight_id,groundspeed,icao24,latitude,longitude,squawk,track,vertical_rate
0,2018-01-01 12:29:49+00:00,11300.0,ARG1511,ARG1511_20180101,309.885195,e06442,-31.449051,-63.963318,7700,130.441641,3008.000000
1,2018-01-01 12:29:50+00:00,11375.0,ARG1511,ARG1511_20180101,310.264709,e06442,-31.450453,-63.961432,7700,130.441641,3040.000000
2,2018-01-01 12:29:51+00:00,11450.0,ARG1511,ARG1511_20180101,310.644223,e06442,-31.451856,-63.959546,7700,130.441641,3072.000000
3,2018-01-01 12:29:52+00:00,11500.0,ARG1511,ARG1511_20180101,311.192793,e06442,-31.452843,-63.958193,7700,130.440361,3074.742857
4,2018-01-01 12:29:53+00:00,11550.0,ARG1511,ARG1511_20180101,311.741363,e06442,-31.453831,-63.956840,7700,130.439081,3077.485714

In [26]:
# settign the columns size 
pd.set_option('display.max_columns', 500)

In [27]:
df.head()

,timestamp,altitude,callsign,flight_id,groundspeed,icao24,latitude,longitude,squawk,track,vertical_rate
0,2018-01-01 12:29:49+00:00,11300.0,ARG1511,ARG1511_20180101,309.885195,e06442,-31.449051,-63.963318,7700,130.441641,3008.000000
1,2018-01-01 12:29:50+00:00,11375.0,ARG1511,ARG1511_20180101,310.264709,e06442,-31.450453,-63.961432,7700,130.441641,3040.000000
2,2018-01-01 12:29:51+00:00,11450.0,ARG1511,ARG1511_20180101,310.644223,e06442,-31.451856,-63.959546,7700,130.441641,3072.000000
3,2018-01-01 12:29:52+00:00,11500.0,ARG1511,ARG1511_20180101,311.192793,e06442,-31.452843,-63.958193,7700,130.440361,3074.742857
4,2018-01-01 12:29:53+00:00,11550.0,ARG1511,ARG1511_20180101,311.741363,e06442,-31.453831,-63.956840,7700,130.439081,3077.485714

 Viewing the first 20 columns

In [28]:
df.head(20)

,timestamp,altitude,callsign,flight_id,groundspeed,icao24,latitude,longitude,squawk,track,vertical_rate
0,2018-01-01 12:29:49+00:00,11300.0,ARG1511,ARG1511_20180101,309.885195,e06442,-31.449051,-63.963318,7700,130.441641,3008.000000
1,2018-01-01 12:29:50+00:00,11375.0,ARG1511,ARG1511_20180101,310.264709,e06442,-31.450453,-63.961432,7700,130.441641,3040.000000
2,2018-01-01 12:29:51+00:00,11450.0,ARG1511,ARG1511_20180101,310.644223,e06442,-31.451856,-63.959546,7700,130.441641,3072.000000
3,2018-01-01 12:29:52+00:00,11500.0,ARG1511,ARG1511_20180101,311.192793,e06442,-31.452843,-63.958193,7700,130.440361,3074.742857
4,2018-01-01 12:29:53+00:00,11550.0,ARG1511,ARG1511_20180101,311.741363,e06442,-31.453831,-63.956840,7700,130.439081,3077.485714
5,2018-01-01 12:29:54+00:00,11600.0,ARG1511,ARG1511_20180101,312.289932,e06442,-31.454818,-63.955487,7700,130.437801,3080.228571
6,2018-01-01 12:29:55+00:00,11650.0,ARG1511,ARG1511_20180101,312.838502,e06442,-31.455806,-63.954134,7700,130.436521,3082.971429
7,2018-01-01 12:29:56+00:00,11700.0,ARG1511,ARG1511_20180101,313.387072,e06442,-31.456794,-63.952781,7700,130.435240,3085.714286
8,2018-01-01 12:29:57+00:00,11750.0,ARG1511,ARG1511_20180101,313.935642,e06442,-31.457781,-63.951429,7700,130.433960,3088.457143
9,2018-01-01 12:29:58+00:00,11800.0,ARG1511,ARG1511_20180101,314.484211,e06442,-31.458769,-63.950076,7700,130.432680,3091.200000
10,2018-01-01 12:29:59+00:00,11850.0,ARG1511,ARG1511_20180101,315.032781,e06442,-31.459756,-63.948723,7700,130.431400,3093.942857
11,2018-01-01 12:30:00+00:00,11900.0,ARG1511,ARG1511_20180101,315.581351,e06442,-31.460744,-63.947370,7700,130.430120,3096.685714
12,2018-01-01 12:30:01+00:00,11950.0,ARG1511,ARG1511_20180101,316.129921,e06442,-31.461731,-63.946017,7700,130.428839,3099.428571
13,2018-01-01 12:30:02+00:00,12000.0,ARG1511,ARG1511_20180101,316.678491,e06442,-31.462719,-63.944664,7700,130.427559,3102.171429
14,2018-01-01 12:30:03+00:00,12050.0,ARG1511,ARG1511_20180101,317.227060,e06442,-31.463707,-63.943311,7700,130.426279,3104.914286
15,2018-01-01 12:30:04+00:00,12100.0,ARG1511,ARG1511_20180101,317.775630,e06442,-31.464694,-63.941958,7700,130.424999,3107.657143
16,2018-01-01 12:30:05+00:00,12150.0,ARG1511,ARG1511_20180101,318.324200,e06442,-31.465682,-63.940605,7700,130.423719,3110.400000
17,2018-01-01 12:30:06+00:00,12200.0,ARG1511,ARG1511_20180101,318.872770,e06442,-31.466669,-63.939253,7700,130.422439,3113.142857
18,2018-01-01 12:30:07+00:00,12250.0,ARG1511,ARG1511_20180101,319.421340,e06442,-31.467657,-63.937900,7700,130.421158,3115.885714
19,2018-01-01 12:30:08+00:00,12300.0,ARG1511,ARG1511_20180101,319.969909,e06442,-31.468644,-63.936547,7700,130.419878,3118.628571

Pulling the last 10 columns

In [29]:
df.tail(10)

,timestamp,altitude,callsign,flight_id,groundspeed,icao24,latitude,longitude,squawk,track,vertical_rate
4344349,2020-01-29 04:09:43+00:00,659.375000,ASH6299,ASH6299_20200129,137.440778,ac2bb8,40.002629,-82.897304,2756,274.590543,-704.0
4344350,2020-01-29 04:09:44+00:00,658.333333,ASH6299,ASH6299_20200129,137.440778,ac2bb8,40.002656,-82.897768,2756,274.590543,-704.0
4344351,2020-01-29 04:09:45+00:00,657.291667,ASH6299,ASH6299_20200129,137.440778,ac2bb8,40.002683,-82.898231,2756,274.590543,-704.0
4344352,2020-01-29 04:09:46+00:00,656.250000,ASH6299,ASH6299_20200129,137.440778,ac2bb8,40.002709,-82.898694,2756,274.590543,-704.0
4344353,2020-01-29 04:09:47+00:00,655.208333,ASH6299,ASH6299_20200129,137.440778,ac2bb8,40.002736,-82.899158,2756,274.590543,-704.0
4344354,2020-01-29 04:09:48+00:00,654.166667,ASH6299,ASH6299_20200129,137.440778,ac2bb8,40.002762,-82.899621,2756,274.590543,-704.0
4344355,2020-01-29 04:09:49+00:00,653.125000,ASH6299,ASH6299_20200129,137.440778,ac2bb8,40.002789,-82.900084,2756,274.590543,-704.0
4344356,2020-01-29 04:09:50+00:00,652.083333,ASH6299,ASH6299_20200129,137.440778,ac2bb8,40.002816,-82.900547,2756,274.590543,-704.0
4344357,2020-01-29 04:09:51+00:00,651.041667,ASH6299,ASH6299_20200129,137.440778,ac2bb8,40.002842,-82.901011,2756,274.590543,-704.0
4344358,2020-01-29 04:09:52+00:00,650.000000,ASH6299,ASH6299_20200129,137.440778,ac2bb8,40.002869,-82.901474,2756,274.590543,-704.0

Pulling a random sample from the rowns list 
- Note this will pull a random et

In [30]:
df.sample(5)

,timestamp,altitude,callsign,flight_id,groundspeed,icao24,latitude,longitude,squawk,track,vertical_rate
3259539,2019-08-24 01:13:12+00:00,33000.000000,ASH6300,ASH6300_20190823,488.347815,ac52f2,35.929064,-86.834418,2463,78.183853,0.0
3396089,2019-09-08 10:24:33+00:00,35977.604167,MSR845,MSR845_20190908,418.370288,0100df,36.313822,9.280334,2013,277.277895,0.0
2672873,2019-06-15 17:42:52+00:00,7891.666667,ROU1911,ROU1911_20190615,253.424596,c07465,55.971359,-5.052213,7700,136.064481,-1408.0
3343965,2019-09-03 23:30:09+00:00,35950.000000,UAL1827,UAL1827_20190903,431.520194,a0acdd,36.813649,-96.586421,0022,255.094241,0.0
2554996,2019-05-29 18:12:28+00:00,37000.000000,EZY15UF,EZY15UF_20190529,489.294989,400c4f,52.559897,-1.663330,6311,156.001842,0.0

Setting a random state for pulling the same

In [34]:
df.sample(frac=0.0001)

,timestamp,altitude,callsign,flight_id,groundspeed,icao24,latitude,longitude,squawk,track,vertical_rate
4294375,2020-01-25 01:38:15+00:00,32000.00000,ICE10K,ICE10K_20200125,456.074161,4cc268,44.364258,-85.146463,7700,50.516131,0.000000
860591,2018-07-20 17:34:24+00:00,39000.00000,ACA548,ACA548_20180720,529.966980,c0293e,49.608119,-105.129499,7700,89.894818,-63.570470
1237317,2018-10-12 10:01:23+00:00,36000.00000,TCX4HR,TCX4HR_20181012,401.642529,4069ea,45.435928,4.493539,5350,353.423506,0.000000
2167483,2019-03-27 22:57:43+00:00,22200.00000,SWA206,SWA206_20190327,350.714681,abb19c,39.364151,-103.867732,5614,300.879704,-704.000000
1778455,2019-01-20 22:40:30+00:00,16575.00000,VOI893,VOI893_20190120,393.904471,a6a11e,32.319168,-97.175226,5521,194.706545,1920.000000
...,...,...,...,...,...,...,...,...,...,...,...
3345825,2019-09-04 00:01:22+00:00,37950.00000,UAL1827,UAL1827_20190903,440.529613,a0acdd,35.637715,-101.010130,4530,251.594043,0.000000
1442048,2018-11-13 16:26:18+00:00,3025.00000,AAL2665,AAL2665_20181113,162.237340,a47903,39.883164,-74.969727,7700,352.918788,-64.000000
3309221,2019-08-28 17:07:29+00:00,34000.00000,DAL2590,DAL2590_20190828,427.055833,ab43c6,36.220184,-94.745407,2044,285.761106,0.000000
321924,2018-04-01 06:23:14+00:00,41000.00000,TRA90W,TRA90W_20180401,434.331295,4841d9,49.415992,2.498089,2115,236.566370,0.000000
3721445,2019-10-29 19:53:41+00:00,10032.53012,ASH6099,ASH6099_20191029,341.940371,ab3e98,29.749309,-94.720946,7700,301.936712,-1990.168675

For reporoducability using the `random_state=XX` ensures the same sample being produced everytime. This is for reproducability of the random data set

In [39]:
df.sample(10, random_state=69)

,timestamp,altitude,callsign,flight_id,groundspeed,icao24,latitude,longitude,squawk,track,vertical_rate
2463923,2019-05-09 22:28:16+00:00,3150.000000,TUI6YX,TUI6YX_20190509,166.508114,3c0ca0,49.005524,2.806514,7700,265.522120,-960.000000
2118286,2019-03-17 15:32:44+00:00,12450.000000,AAL163,AAL163_20190317,351.001121,acd5ad,33.644485,-118.304761,2454,90.163235,2432.000000
3876186,2019-11-21 13:55:23+00:00,12550.000000,SKW5639,SKW5639_20191121,317.165298,abb645,38.644272,-104.356265,2132,105.746712,2560.000000
31081,2018-01-08 03:59:14+00:00,32000.000000,DAL65,DAL65_20180108,413.707494,ab2855,34.367789,-114.634719,3575,257.129758,0.000000
1554593,2018-12-06 14:34:46+00:00,37000.000000,ABY1692,ABY1692_20181206,510.407239,8964da,23.104523,55.245051,1751,36.555582,-64.000000
628528,2018-06-05 07:08:42+00:00,36975.000000,AAL213,AAL213_20180605,467.646244,a3deca,11.747875,-66.879717,3655,145.890354,0.000000
1302600,2018-10-23 09:40:04+00:00,32000.000000,EVA011,EVA011_20181023,479.549375,8990d7,40.961435,-127.271930,7336,328.298570,0.000000
3179997,2019-08-13 08:50:05+00:00,37975.000000,RAM718D,RAM718D_20190813,483.698869,020027,42.208774,-1.228808,6474,51.969181,0.000000
780071,2018-06-30 09:44:43+00:00,34950.000000,DAL819,DAL819_20180630,468.670055,a3d3f0,34.472491,-95.946407,7256,81.904476,0.000000
2893199,2019-07-08 18:53:11+00:00,27616.666667,JIA5116,JIA5116_20190708,488.007319,a653f6,37.784871,-87.356074,7700,103.450049,682.666667

In [40]:
# View only columns 
df.columns

Index(['timestamp', 'altitude', 'callsign', 'flight_id', 'groundspeed',
       'icao24', 'latitude', 'longitude', 'squawk', 'track', 'vertical_rate'],
      dtype='object')

In [43]:
# View Index
df.index
df2.index

RangeIndex(start=0, stop=4344359, step=1)

In [44]:
df2.index

RangeIndex(start=0, stop=4344359, step=1)

View information about the dataset,
- `verbose=True` - Gives more detailed information

In [47]:
# getting info of the data set 
df2.info(verbose=True) , Explains the entire dataste

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4344359 entries, 0 to 4344358
Data columns (total 11 columns):
 #   Column         Dtype
---  ------         -----
 0   timestamp      object
 1   altitude       float64
 2   callsign       object
 3   flight_id      object
 4   groundspeed    float64
 5   icao24         object
 6   latitude       float64
 7   longitude      float64
 8   squawk         int64
 9   track          float64
 10  vertical_rate  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 364.6+ MB

In [49]:
df.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4344359 entries, 0 to 4344358
Columns: 11 entries, timestamp to vertical_rate
dtypes: datetime64[us, UTC](1), float64(6), object(4)
memory usage: 364.6+ MB

In [51]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4344359 entries, 0 to 4344358
Data columns (total 11 columns):
 #   Column         Dtype
---  ------         -----
 0   timestamp      object
 1   altitude       float64
 2   callsign       object
 3   flight_id      object
 4   groundspeed    float64
 5   icao24         object
 6   latitude       float64
 7   longitude      float64
 8   squawk         int64
 9   track          float64
 10  vertical_rate  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 364.6+ MB

## 2.1 DescriptiveStatistics <a class="anchor" id="s4"></a> [↩️TOC](#toc)

In [52]:
# gettingg descriptive statistics 

df.describe()

,altitude,groundspeed,latitude,longitude,track,vertical_rate
count,4.344359e+06,4.307312e+06,4.344359e+06,4.344359e+06,4.307312e+06,4.307312e+06
mean,2.653439e+04,3.944624e+02,4.010783e+01,-4.393507e+01,1.927143e+02,-3.354702e+01
std,1.212769e+04,1.285338e+02,1.492686e+01,5.537757e+01,1.062650e+02,1.772641e+03
min,-5.750000e+02,2.828425e+00,-3.866559e+01,-1.565582e+02,0.000000e+00,-2.302500e+05
25%,1.647500e+04,3.398423e+02,3.549571e+01,-9.158867e+01,9.294816e+01,-6.400000e+01
50%,3.200000e+04,4.186379e+02,4.220419e+01,-6.188072e+01,2.094500e+02,0.000000e+00
75%,3.600000e+04,4.637420e+02,4.920561e+01,1.862626e+00,2.851302e+02,0.000000e+00
max,1.155000e+05,4.535941e+03,6.682288e+01,1.764965e+02,3.600000e+02,1.235200e+04

In [53]:
# Getting descriptive statistics 
df2.describe()

,altitude,groundspeed,latitude,longitude,squawk,track,vertical_rate
count,4.344359e+06,4.307312e+06,4.344359e+06,4.344359e+06,4.344359e+06,4.307312e+06,4.307312e+06
mean,2.653439e+04,3.944624e+02,4.010783e+01,-4.393507e+01,4.830309e+03,1.927143e+02,-3.354702e+01
std,1.212769e+04,1.285338e+02,1.492686e+01,5.537757e+01,2.664628e+03,1.062650e+02,1.772641e+03
min,-5.750000e+02,2.828425e+00,-3.866559e+01,-1.565582e+02,0.000000e+00,0.000000e+00,-2.302500e+05
25%,1.647500e+04,3.398423e+02,3.549571e+01,-9.158867e+01,2.265000e+03,9.294816e+01,-6.400000e+01
50%,3.200000e+04,4.186379e+02,4.220419e+01,-6.188072e+01,5.376000e+03,2.094500e+02,0.000000e+00
75%,3.600000e+04,4.637420e+02,4.920561e+01,1.862626e+00,7.700000e+03,2.851302e+02,0.000000e+00
max,1.155000e+05,4.535941e+03,6.682288e+01,1.764965e+02,7.777000e+03,3.600000e+02,1.235200e+04